server:
  port: 8768
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/