server:
  port: 8766

spring:
  thymeleaf:
    prefix: classpath:/static
    suffix: .html
  application:
    name: client
eureka: 
  client: 
   service-url:
      defaultZone: http://localhost:8761/eureka/
